FROM bde2020/flink-maven-template:1.14.5-hadoop3.2

ENV FLINK_APPLICATION_JAR_NAME afwcc
ENV FLINK_APPLICATION_MAIN_CLASS DataStreamJob
ENV FLINK_APPLICATION_ARGS "--input ./example1.requests --output ./out.wcc"